services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
      - MY_PROJECT="Hello World"
      - DATABASE_URL=postgresql://dbuser:db-password@db_service:5432/mydb
      #- API_KEY=your-api-key-here
    env_file:
      - .env.sample
    volumes:
      - ./backend/src:/app
    depends_on:
      db_service:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: restart
          path: ./backend/src
        - action: rebuild
          path: ./backend/Dockerfile

  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=mydb
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dc_managed_db_volume: